apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fg76ultpn-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0682e84a2e.uhxk.p3.openshiftapps.com/rhtap/rhtap-qe:1e535b574f2168bb3604452e4f30da57d2a8f887@sha256:f226e0961f218805b4b92bb4ba5e8ecd72312e27f473b29617327a3e0480e20b
          name: container-image
